import hashlib
import json
from datetime import datetime
from pathlib import Path

import deepseek_user_insight as dsui
from session_runtime import SessionFile, reserve_api_call


BASE_DIR = Path(__file__).resolve().parent
CACHE_PATH = SessionFile("strategy_onepage_cache.json")
CACHE_SCHEMA_VERSION = "strategy-launch-v3"


def _cache_store():
    if not CACHE_PATH.exists():
        return {}
    try:
        data = json.loads(CACHE_PATH.read_text(encoding="utf-8"))
        return data if isinstance(data, dict) else {}
    except Exception:
        return {}


def cache_key(payload):
    # The same data context generated by a different model is a distinct cache entry.
    model = dsui.api_config().get("model", "")
    raw = json.dumps(
        {"schema": CACHE_SCHEMA_VERSION, "model": model, "payload": payload},
        ensure_ascii=False,
        sort_keys=True,
        default=str,
    )
    return hashlib.sha1(raw.encode("utf-8")).hexdigest()


def get_cached_strategy(payload):
    row = _cache_store().get(cache_key(payload))
    return row.get("result") if isinstance(row, dict) else None


def get_cached_record(payload):
    row = _cache_store().get(cache_key(payload))
    return row if isinstance(row, dict) else None


def _validate(result):
    if not isinstance(result, dict):
        raise ValueError("AI 返回格式异常，请重试")
    if not isinstance(result.get("主结论"), str) or not result["主结论"].strip():
        raise ValueError("AI 返回格式异常：缺少主结论")
    opportunities = result.get("关键机会点")
    strategies = result.get("核心策略")
    stages = result.get("阶段计划")
    tasks = result.get("角色任务")
    if not isinstance(opportunities, list) or len(opportunities) != 3:
        raise ValueError("AI 返回格式异常：关键机会点必须为3项")
    if not isinstance(strategies, list) or not 1 <= len(strategies) <= 3:
        raise ValueError("AI 返回格式异常：核心策略必须为1-3项")
    if not isinstance(stages, list) or len(stages) != 4:
        raise ValueError("AI 返回格式异常：阶段计划必须为4项")
    if not isinstance(tasks, list) or not tasks:
        raise ValueError("AI 返回格式异常：缺少角色任务")
    required_opportunity = {"机会类型", "机会名称", "关键依据", "落地建议"}
    required_strategy = {"策略名称", "策略目标", "策略路径"}
    required_stage = {"阶段", "时间", "阶段目标"}
    required_task = {"角色", "任务", "开始阶段", "结束阶段", "交付物", "衡量指标"}
    if any(not isinstance(item, dict) or not required_opportunity.issubset(item) for item in opportunities):
        raise ValueError("AI 返回格式异常：机会点字段不完整")
    if any(not isinstance(item, dict) or not required_strategy.issubset(item) for item in strategies):
        raise ValueError("AI 返回格式异常：核心策略字段不完整")
    if any(not isinstance(item, dict) or not required_stage.issubset(item) for item in stages):
        raise ValueError("AI 返回格式异常：阶段计划字段不完整")
    if any(not isinstance(item, dict) or not required_task.issubset(item) for item in tasks):
        raise ValueError("AI 返回格式异常：角色任务字段不完整")
    return result


def _json_with_duplicate_keys(raw):
    """Recover a response that merged three opportunity objects via duplicate keys."""
    def keep_pairs(pairs):
        obj = {}
        for key, value in pairs:
            if key not in obj:
                obj[key] = value
            elif isinstance(obj[key], list) and obj[key] and obj[key][0] == "__duplicate_values__":
                obj[key].append(value)
            else:
                obj[key] = ["__duplicate_values__", obj[key], value]
        return obj

    result = json.loads(raw, object_pairs_hook=keep_pairs)
    opportunities = result.get("关键机会点") if isinstance(result, dict) else None
    if isinstance(opportunities, list) and len(opportunities) == 1 and isinstance(opportunities[0], dict):
        merged = opportunities[0]
        fields = ("机会类型", "机会名称", "关键依据", "落地建议")
        values = {}
        for field in fields:
            value = merged.get(field)
            values[field] = value[1:] if isinstance(value, list) and value and value[0] == "__duplicate_values__" else [value]
        count = max(len(items) for items in values.values())
        if count == 3 and all(len(items) == count for items in values.values()):
            result["关键机会点"] = [{field: values[field][index] for field in fields} for index in range(count)]
    return result


def generate_strategy(payload):
    config = dsui.api_config()
    if not config["api_key"]:
        raise RuntimeError("暂未检测到 DeepSeek API Key，请在项目根目录 .env 文件中配置 DEEPSEEK_API_KEY。")
    if dsui.OpenAI is None:
        raise RuntimeError("缺少 openai 依赖，请先安装 requirements.txt 中的依赖。")
    schema = {
        "主结论": "",
        "关键机会点": [
            {"机会类型": "市场机会", "机会名称": "", "关键依据": "", "落地建议": ""},
            {"机会类型": "竞争机会", "机会名称": "", "关键依据": "", "落地建议": ""},
            {"机会类型": "用户转化机会", "机会名称": "", "关键依据": "", "落地建议": ""},
        ],
        "核心策略": [
            {"策略名称": "", "策略目标": "", "策略路径": ""}
        ],
        "阶段计划": [
            {"阶段": "预热期", "时间": "上市前4-2周", "阶段目标": ""},
            {"阶段": "上市期", "时间": "上市前1周至上市周", "阶段目标": ""},
            {"阶段": "转化期", "时间": "上市后1-4周", "阶段目标": ""},
            {"阶段": "复盘期", "时间": "上市后5-6周", "阶段目标": ""},
        ],
        "角色任务": [
            {"角色": "市场/内容", "任务": "", "开始阶段": "预热期", "结束阶段": "转化期", "交付物": "", "衡量指标": ""}
        ]
    }
    system = (
        "你是汽车行业GTM策略负责人。只能依据输入的市场、竞争和用户摘要生成策略一页纸，不得补造数据。"
        "输出必须短、准、可执行，不重复解释完整分析过程，不输出Markdown，只输出合法JSON。"
        "主结论必须以用户输入的最终策略目标为终点，依次说明聚焦哪类用户、在哪个细分或区域市场、发挥产品什么优势、通过哪些销售转化动作达成目标。"
        "主结论限一句；关键依据必须写明具体价格、车身、能源或区域机会，并点名核心竞品及其相对优劣；"
        "落地建议必须是可执行动作。核心策略1-3项。任务只能分配给输入中已选择的参与角色，并尊重其职责。"
    )
    prompt = (
        "严格按以下结构输出。关键机会点数组必须包含3个彼此独立的JSON对象，禁止把三组字段合并进同一个对象；"
        "机会点顺序固定为市场机会、竞争机会、用户转化机会；阶段固定为预热期、上市期、转化期、复盘期。"
        "预热期用于新品预热、作战计划、用户触达和产品培训；上市期用于专家邀约、到店、试驾和订单转化；"
        "转化期用于上市后的门店运营、日常追盯和用户跟进；复盘期用于上市总结、效果归因与动作迭代。"
        "角色任务需要覆盖所有已选择角色，允许跨阶段并行，任务应具体到海报、内容、活动、试驾、邀约、数据复盘等可交付动作：\n"
        + json.dumps(schema, ensure_ascii=False)
        + "\n已有摘要数据：\n"
        + json.dumps(payload, ensure_ascii=False, default=str)
    )
    client = dsui.OpenAI(api_key=config["api_key"], base_url=config["base_url"], timeout=60, max_retries=0)
    reserve_api_call()
    response = client.chat.completions.create(
        model=config["model"],
        messages=[{"role": "system", "content": system}, {"role": "user", "content": prompt}],
        response_format={"type": "json_object"},
        extra_body={"thinking": {"type": "disabled"}},
        temperature=0.2,
        max_tokens=3600,
    )
    raw = response.choices[0].message.content or ""
    try:
        result = _validate(_json_with_duplicate_keys(raw))
    except Exception as exc:
        error_path = BASE_DIR / "deepseek_strategy_error_log.txt"
        error_path.write_text(f"{datetime.now().isoformat()}\n{raw}\n{exc}\n", encoding="utf-8")
        raise ValueError("AI 返回格式异常，请重试") from exc
    store = _cache_store()
    store[cache_key(payload)] = {"result": result, "model": config["model"], "generated_at": datetime.now().isoformat()}
    CACHE_PATH.write_text(json.dumps(store, ensure_ascii=False, indent=2), encoding="utf-8")
    return result
